Repository FusionAuth/fusionauth-react-sdk, pull requests merged in 2024-02, with the labels that each got.

#63 Fix RequireAuth tests causing 'act(...)' warning
  src/__tests__/RequireAuth.test.tsx
Labels: bug

#61 Fix issue where failed request to /me causes infinite loop
  src/__tests__/FusionAuthProvider.test.tsx
  src/providers/FusionAuthProvider.tsx
Labels: bug

#70 Update Changes markdown for 1.0.0 release
  CHANGES.md
  package.json
Labels: documentation

#76 adds node/npm version to package.json
  .nvmrc
  package-lock.json
  package.json
Labels: general issue

#74 adds source maps
  webpack.config.js
Labels: enhancement

#73 removes yarn.lock (duplicate lock file)
  package-lock.json
  yarn.lock
Labels: general issue

#69 set `isAuthenticated` when `user` is set
  src/__tests__/FusionAuthProvider.test.tsx
  src/providers/FusionAuthProvider.tsx
Labels: bug

#78 adds error handling to main provider
  src/__tests__/FusionAuthProvider.test.tsx
  src/providers/FusionAuthProvider.tsx
Labels: bug

#81 removes async definitions for non-async functions
  src/__tests__/FusionAuthProvider.test.tsx
  src/providers/FusionAuthProvider.tsx
Labels: general issue

#84 fixes usage of `waitFor` to render component tests
  src/__tests__/FusionAuthLoginButton.test.tsx
  src/__tests__/FusionAuthLogoutButton.test.tsx
  src/__tests__/FusionAuthRegisterButton.test.tsx
  src/__tests__/mocks/createContextMock.ts
  src/__tests__/withFusionAuth.test.tsx
Labels: general issue

#85 adds option to set custom at_exp cookie name
  src/providers/FusionAuthProvider.tsx
Labels: enhancement
